### ISSUE TITLE
SolidDataset should implement DatasetCore

### ISSUE THREAD

**Issue by ianconsolata** [inrupt/solid-client-js#1256]
### Search terms you've used
DatasetCore

### Feature suggestion

SolidDatasets do not currently implement either the Dataset interface, nor the DatasetCore interface. This make it very difficult to use existing RDF libraries with SolidDatasets, since many of them expect DatasetCore. In a couple places in our application, we create a DatasetCore from the quads in a given SolidDataset manually, and it seems to continue to work just fine as both a DatasetCore and a SolidDataset. However, doing it manually does not seem like good practice. It would be nice if this library supported that transformation for us.

### Expected functionality/enhancement
Ideally the SolidDataset interface would be an extension of the DatasetCore interface. All DatasetCore methods would be supported on SolidDatasets. I think this is the best developer experience, however, I don't think it is possible. SolidDatasets are supposed to be ImmutableDatasets, and DatasetCore explicitly requires mutation with `add` and `delete`. Even if implementing the full DatasetCore standard is impossible, it would be convenient to have support in SolidDataset for the immutable DatasetCore methods (like `match` and `has`).

A more practical solution would be a set of convenience methods that allow the developer to easily transform to and from an equivalent DatasetCore, perhaps using signatures similar to the one below:

```
function asDatasetCore(dataset: SolidDataset): DatasetCore {...}
function fromDatasetCore(dataset: DatasetCore): SolidDataset {...}
```

This would maintain the immutability of SolidDataset, while allowing developers to easily get a mutable DatasetCore copy they could use in libraries that expect a DatasetCore.

### Actual functionality/enhancement
SolidDataset is a custom type defined by the Inrupt client library (ImmutableDataset) with no clear mapping or relationship to the DatasetCore RDF standard.

### Use Cases

- I would like to be able to use the Inrupt client library to fetch and deserialize a SolidDataset, but then use that dataset in a variety of other RDF search, traversal, matching, and reasoner libraries that expect a DatasetCore (i.e. `clownface`).
- I would like to be able to use useful functions like `match` that are part of the DatasetCore specification on SolidDatasets.

**Comment by Vinnl** [comment]
It's not publicly documented (yet), but solid-client does actually include those! `import { fromRdfJsDataset, toRdfJsDataset } from "@inrupt/solid-client";`

**Comment by pmcb55** [comment]
Hiya @ianconsolata, yeah, you've certainly highlighted a known problem there, and explained it extremely well.

A little history - `SolidDataset` did _originally_ extend `DatasetCore`, as obviously we, like you, want `solid-client` to fit naturally with all the other existing RDF tooling out there today, and therefore it really should directly (i.e., without translators or converters) support the 'standard' RDF/JS interfaces that everything else already uses. (Technically RDF/JS isn't an official 'standard', but I know what you mean, i.e., for all intents and purposes it can certainly be considered one today in JavaScript-land).

But as you rightly point out, immutability was deemed to be even more important, and so we decided (reluctantly!) to break that contract (because immutability is so crucial a capability for all the state management systems used by the major client-side UI frameworks today (e.g., React, Vue, AngularJS)).

And so yeah, today `solid-client` no longer plays so nicely with all the existing RDF tooling out there, and so the `to()` and `from()` functions are the best option for now (unfortunately for you, and all the other RDF practitioners out there).

Ideally we would have first discussed with the RDF/JS community the possibility of updating the RDF/JS interfaces to offer explicit support for both mutable and immutable datasets. We were going to offer suggestions for such interface changes, but we never got around to that, as we just didn't have the time (and I've no idea how active the RDF/JS community is these days anyway, or whether they'd be interested in discussing such potentially major changes (which could take a long time to discuss and decide on, and then a further long time for implementations to be upgraded)).

But if you were interested in pursuing such a discussion with the RDF/JS community (with a view to RDF/JS interfaces supporting immutable datasets), then you'd certainly have our active support in that effort :) !

**Comment by ianconsolata** [comment]
I think for now converting between the two is sufficient. I generally don't like mutable types, so now that I have a better understanding of what is going on I appreciate the separation. For now, `SolidDataset` seems like a perfectly valid alternative. It would be nice if it supported an immutable `matches` eventually though, i.e. one that returned a new `SolidDataset`, so that I don't have to convert just to query it. Unless there is some easy way to run more complex `matches` style RDF queries on SolidDatasets that I don't know about.
