### ISSUE TITLE
New node version: Expected version "^14.17.0 || ^16.0.0". Got "18.12.1"

### ISSUE THREAD

**Issue by aharth** [inrupt/solid-client-js#1775]
### Search terms you've used

is:issue node 

### Bug description

The library is not compatible with the latest stable Node.js version (18.12.1 LTS).

In a project with solid-client as dependency, I get the following error with yarnpkg install:

````
error @inrupt/solid-client@1.23.3: The engine "node" is incompatible with this module. Expected version "^14.17.0 || ^16.0.0". Got "18.12.1"
error Found incompatible module.
````

### To Reproduce

1. Try to build a project using solid-client on the latest Node.js LTS version

### Expected result

 

I would expect the library to be compatible with the current Node.js version.

### Actual result

I get an error message with yarnpkg install and the build process stops.

### Environment

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

  System:
    OS: Linux 6.0 Debian GNU/Linux bookworm/sid
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 10.45 GB / 15.52 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 9.1.2 - /usr/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Chromium: 107.0.5304.110
    Firefox: 102.5.0esr
  npmGlobalPackages:
    @openapitools/openapi-generator-cli: 2.5.2
    browserify: 16.5.0
    jsonld-cli: 0.3.0
    solid-curl: 0.1.7
    twilio: 3.29.1

```

**Comment by NSeydoux** [comment]
Hello @aharth, thanks for reaching out. That is correct, unfortunately we don't support Node 18 at the moment. We are working on getting this support in, but it is a non-trivial task for our authentication library, because of changes to `fetch` in Node 18, which are welcome but require some work to be merged in. https://github.com/inrupt/solid-client-authn-js/issues/2374 is related.

When we have support for Node 18 across our libraries, we'll update this issue.

**Comment by sbuchok** [comment]
I asked if we could just get the JS files instead of needing NPM but was basically told no. So, I started down this road of following their documentation and immediately got this error as well. 

I'm using the latest version of VS 2022 (17.4.1)
Opened the console and  npm install @inrupt/solid-client

npm : npm WARN notsup Unsupported engine for @inrupt/solid-client@1.23.3: wanted: {"node":"^14.17.0 || ^16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
At line:1 char:1
+ npm install @inrupt/solid-client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN notsup...npm":"6.14.4"}):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm WARN notsup Not compatible with your version of node/npm: @inrupt/solid-client@1.23.3
npm WARN notsup Unsupported engine for readable-stream@4.2.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: readable-stream@4.2.0
npm WARN Solid No description
npm WARN Solid No repository field.
npm WARN Solid No license field.


**It would be appreciated if you guys would just provide the JS files for those who don't want to wait for you guys to fix the build chain and for the people who want to go through the pain of using NPM, let them.**

**Comment by ThisIsMissEm** [comment]
@sbuchok you're using a deprecated version of Node.js, the last part says you're using 12.x which was deprecated as end-of-life on 2022-04-30, meaning after this date it is no longer even supported by the Node.js project. Please upgrade to Node.js 16 (it can be downloaded here: https://nodejs.org/download/release/latest-v16.x/ )

```
npm WARN notsup Unsupported engine for readable-stream@4.2.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"}
(current: {"node":"12.18.0","npm":"6.14.4"})
```

We only support Node.js ^14.17.0 or ^16.0.0, we do not support 12.x or 18.x.

Node.js 18.x support is coming, but technically complicated (we have to migrate to a new fetch library to take advantage of the native fetch support in node.js 18.x, and that requires reworking all our unit tests)

**Comment by sbuchok** [comment]
I just realized I totally highjacked this thread, ignore what I wrote above. Please see https://github.com/inrupt/solid-client-js/issues/1777 instead.

**Comment by aharth** [comment]
Any news on the update to Node 18?  I would be happy with an older version of the fetch library for the moment.

**Comment by elf-pavlik** [comment]
> The remaining Inrupt libraries are at similar stages of support for Node 18.

In https://github.com/inrupt/solid-client-authn-js/issues/2374#issuecomment-1499617633 I suggested adding node 20 as soon as it gets released in one week (2023-04-18)

**Comment by jeswr** [comment]
Node 18 is now supported as of 1.27. Work to check for compatiblity with Node 20 across our libraries is underway.

**Comment by derwehr** [comment]
This seems related:
Node 21 is not supported. When trying to install `@inrupt/solid-client-authn-core@2.1.0` using node 21.x.x I get the error `The engine "node" is incompatible with this module. Expected version "^18.0.0 || ^20.0.0". Got "21.6.2"`.

**Comment by NSeydoux** [comment]
Hi @derwehr, thanks for reaching out.

Odd versions of Node are not suited for production, they are development versions used by the NodeJS team. We do not support these, and only ever test against even versions, which is why you are experiencing this error. I'm not sure it blocks anything from installing, but it is letting you know that unexpected errors may happen because of the target NodeJS version. If you do not have a specific reason to be on a development version, I would advise to use a stable note version (i.e. 20.x, and not 21.x).
