### ISSUE TITLE
Please provide a Zero dependency way to use the libraries

### ISSUE THREAD

**Issue by sbuchok** [inrupt/solid-client-js#1781]
Currently you only allow the installation/use of the library using NPM (that I am aware of). Please provide a way to use these libraries without the need for any dependencies or build tools. Just the JS files would be preferred.

By doing this, you are opening the library to a wider audience.

I have already run into issues installing it using the latest version of Node and will try with a lower version, however, once I get the JS files, that's all I really want. I don't care about TypeScript or NPM or anything else. Since this is a JavaScript library, I should be able to use the import statement to bring it in to any project I want with or without NPM as part of the build chain.

I know you guys have already said that this isn't something you will do now, so I am making this a feature request as I would like to see this become more accessible to all types of projects, not just those that use NPM.

**Comment by ThisIsMissEm** [comment]
We have already explained at length in various issues, a lot of which you have reported, that we will not be doing this: npm is the standard distribution for javascript packages today, whilst you may not be willing to learn to work with the tools, we won't be taking on the extra work required for this.

please refrain from opening another issue like this in the future, an answer has already been given.

**Comment by sbuchok** [comment]
My understanding was that you wouldn't be doing this now. This was brought up in a bug ticket. I decided it was probably better for me to create a feature request. As this is a feature I would like to see. If you guys are just going to outright say "No, we will never do this", then fine. Please close this ticket. 

I currently work at a place that builds software for governments and we do not use NPM. I was hoping to get something working without the need for NPM so that I could pitch this as an authentication alternative. Since our customers are government, I was hoping that this would allow solid some more recognition. 

I won't open another ticket, but this is disappointing to hear.

**Comment by ThisIsMissEm** [comment]
Okay, so let's look at it this way: In order to support this, we would need to:
- add complexity to our rollup.js configuration, likely pulling in a lot of additional development dependencies (such as babel) in order to output a single-file build
- But, that alone wouldn't be enough as we'd need to compile in all our dependencies (n3, jose, json-ld, rdfjs, etc), and we'd have to deal with complexities in that, e.g., how are optional dependencies managed?
- We'd then need infrastructure in place for somewhere to publish these files to, we'd need operations support to ensure those are highly available and auditable
- We'd need budget approved for serving these assets via a CDN, such that you could just use a script tag.
- We'd need a way to publish the [subresource integrity checksums](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity), such that your page knows that the javascript being served to it is actually the javascript we published
- we'd need to figure out the version strategy and how to notify you of exploits or vulnerabilities, because those do happen from time to time in any code.
- We'd need to ensure that this all happens from our build/release pipeline.
- And even then, you'd still have to adjust content security policies to allow our CDN origin to load scripts on your pages.

All these concerns are currently taken care of by using npm.

If your concern is "there's too much unaudited code on npm", then there's ways to workaround that, e.g., by running your own mirror of npm with just approved modules on it via verdaccio, or using npm's organisation tools to provide approved package lists.

At the end of the day, npm and build tools have become part of the javascript ecosystem and how modern javascrIpt is distributed and consumed. The days of "include a jquery script tag in my page" have been long gone for a significant part of the industry.

This is no small amount of work. On the surface it might seem easy, but once you dig deeper on the security, auditable, availability, and tooling required, you start to appreciate npm & all that it provides.

**Comment by ThisIsMissEm** [comment]
Also, as a side note: Solid is much much more than just a means to authenticate.

**Comment by sbuchok** [comment]
I understand it would take some effort. That's why it's a feature request.
**The days of "include a jquery script tag in my page" have been long gone for a significant part of the industry.** - Every site that uses JavaScript has a script tag. 

I also understand that solid is more than authentication, but that is where I wanted to start.

My main point is that if you guys are able to supply just the JS files, this would reach everyone, not just people who use NPM. Sure, I can see that NPM helps you guys build this, but it doesn't help everyone consume it is my point. And isn't that ultimately what you guys want.

Thanks.
