### ISSUE TITLE
unstable_fetchResourceInfoWithAcl does not return type information, or webIds for ACL

### ISSUE THREAD

**Issue by daytonn** [inrupt/solid-client-js#203]
The new API for fetching resource information without a full request (`unstable_fetchResourceInfoWithAcl`) does not return the information needed for our use-case. Currently it does not return the type information of the given resource and it appears to have a simplified ACL.

The desired information received from this call the following:

- The type of the resource
- All permissions granted to the resource and the webIds associated with the permissions (so we can display profile info for each permitted party)
- Fallback permissions

If I were to put this data into a JSON object, it would look something like this:

```json
{
  "type": "http://www.w3.org/ns/ldp#BasicContainer",
  "acl": {
    "https://dayton.dev.inrupt.net/profile/card#me": {
      "read": true,
      "write": true,
      "append": true,
      "control": true,
    },
    "https://ajacksified-dev.dev.inrupt.net/profile/card#me": {
      "read": true,
      "write": true,
      "append": true,
      "control": false,
    },
    "fallbackAcl": {
      "read": true,
      "write": false,
      "append": false,
      "control": false,
    }
  }

}
```

**Comment by NSeydoux** [comment]
Hi Dayton, 

I have a couple of questions to be sure to implement the fix correctly. 

1. For the `type` property, what are the values you would expect ? My guess is  `http://www.w3.org/ns/ldp#BasicContainer`, `http://www.w3.org/ns/ldp#DirectContainer` (or even just `http://www.w3.org/ns/ldp#Container`), and for non-container either the content type (e.g. `	image/jpeg`), or `http://www.w3.org/ns/ldp#Resource` if the content-type is a supported RDF serialization (`text/turtle`, `application/json+ld`, `application/rdf+xml`) and the content type otherwise
2. To get the permissions associated to each WebID stipulated in the ACL, would something along those lines address the issue: 
```typescript
const myResourceInfo = await unstable_fetchResourceInfoWithAcl("http://my.pod/my-resource");
const accessModeList = unstable_getAgentAccessModesAll(myResourceInfo)
```
With `accessModeList` containing an association between WebIDs and permissions? Public access isn't currently handled, so you only would have a list of WebIDs to whom access is granted explicitly, in the ACL attached to the resource if any or via its parent default settings otherwise.

**Comment by Vinnl** [comment]
I think the `type` issue is already logged in #163, right?

**Comment by NSeydoux** [comment]
I think so, but depending on @daytonn's answer I think #163 may require to be updated: from an app perspective, I expect that having the information that a given resource is a container is more informative than knowing it is serialized in turtle, but that's an a-priori I'd want to confirm. And according to #163, the `rel=type` Link header isn't necessarily present/reliable, is that correct ?

**Comment by Vinnl** [comment]
Yeah I updated that issue to also indicate whether a Resource is a Container or not. As I understand it, they need both: display whether something is a Container or a non-Container Resource, and determine whether they need to show the Resource (Container or non-Container) to the user or offer a download link.

And yes, it didn't sound like we can count on that Link header being available in Solid.

**Comment by ajacksified** [comment]
> I updated that issue to also indicate whether a Resource is a Container or not. As I understand it, they need both: display whether something is a Container or a non-Container Resource, and determine whether they need to show the Resource (Container or non-Container) to the user or offer a download link.

I would think `type` returns an IRI (`http://www.w3.org/ns/ldp#BasicContainer`, `http://www.w3.org/ns/ldp#Resource`, etc), and you would also, separately expose a `contentType` property with the value of the mime-type of a resource as returned by the Content-Type header (such as `image/jpeg`). This way, the library doesn't have to make any determination of what the most "correct" type is to show. Our logic would then be essentially, in pseudocode:

```javascript
if (CONTAINER_TYPES.include(resource.type)) {
  displayContainerLink();
} else {
  displayContent(resource.iri, resource.contentType);
}
```

(The library could also potentially expose an `isContainer` boolean on resourceInfo.)

Regarding the ACL, your example seems reasonable to me:

```javascript
const myResourceInfo = await unstable_fetchResourceInfoWithAcl("http://my.pod/my-resource");
const accessModeList = unstable_getAgentAccessModesAll(myResourceInfo);
```

**Comment by pmcb55** [comment]
Just to note on that example `if` statement - I'd suggest also relying on the resource type being either an RDF resource or a Non-RDF Resource, and only falling back to the Content-Type for Non-RDF Resources (i.e. for RDF Resources the Content-Type really shouldn't matter, as any RDF parsing library should be able to parse any compliant RDF serialization media-type).

**Comment by ajacksified** [comment]
We're currently relying on the `headers` object being returned from `fetchFile`; if you returned the headers, instead of a smaller subset of the headers, that would allow us to continue to read the content-type.

**Comment by Vinnl** [comment]
> I would think type returns an IRI (http://www.w3.org/ns/ldp#BasicContainer, http://www.w3.org/ns/ldp#Resource, etc), 

Ideally the type-specific discussions would be consolidated in the existing #163, but since we're here... I think here you are referring to the `rdf:type` predicates exposed about a Resource in its Container, but unfortunately, we cannot rely on that information being available when fetching a single Resource, because we cannot be sure that we have access to its Container. (And of course, that would require an _additional_ HTTP request, which also isn't great.)

For your use case I don't think that should matter a lot, since you're typically fetching the Container's data _before_ fetching the Resource data, right? So if you wanted the type of `https://vincent-test.inrupt.net/public/someresource`, you could do:

```typescript
const containerDataset = await fetchLitDataset('https://vincent-test.inrupt.net/public/');
const container = getThingOne(containerDataset, 'https://vincent-test.inrupt.net/public/');
// The IRI's returned by getIriAll have their own LitDatasets, but containerDataset _also_ contains Things with their IRIs:
const containerChildrenMetadata = getIriAll(container, ldp.contains).map(childIri => getThingOne(containerDataset, childIri);

console.log('Types of first child:', getIriAll(containerChildrenMetadata[0], rdf.type);
```

#163 contains more details on how we can at least determine whether a Resource contains RDF or not. We should be able to set an `isContainer` boolean by simply checking whether the Resource's IRI ends in a `/`.

> Regarding the ACL, your example seems reasonable to me:

Note that that example is already possible today :)

**Comment by ajacksified** [comment]
> So if you wanted the LDP type (not Content-Type) 

Afaik, we only need it to determine whether a resource is a container ahead of time, so if:

> We should be able to set an isContainer boolean by simply checking whether the Resource's IRI ends in a /.

That solves our problem. Someday, we may need to determine whether a container is a IndirectContainer, but we don't at the moment. (Maybe by then, the spec will include a Link header with type?)

> Note that that example is already possible today :)

I wasn't sure if it required changes. @daytonn, see the above ☝️

**Comment by daytonn** [comment]
@NSeydoux I think that would suffice to solve the issue. The main thing we're trying to accomplish is to get this basic meta data without a lot of heavyweight requests. What you've proposed seems reasonable to me. Regarding the types, like @ajacksified mentioned I think we'd want the iri of the type and also a `contentType`. This will helps us understand and be able to "consume" resources more efficiently.

**Comment by ajacksified** [comment]
@daytonn do you think we need the type of the iri - or is knowing whether it's a `Container` or not sufficient, and then we can rely on content-type to know how to display the resource if it isn't a `Container`?

**Comment by daytonn** [comment]
@ajacksified If we can easily get the type of the iri, I would add it. If this adds too much complexity then we can get by like you mentioned using the content-type.

**Comment by Vinnl** [comment]
I think this is resolved by:

- [`isContainer`](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/_resource_resource_.html#iscontainer)
- [`getContentType`](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/_resource_resource_.html#getcontenttype)
- [`getAgentAccessAll`](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/_acl_agent_.html#getagentaccessall)

So I'm closing this issue - feel free to reopen if something's not addressed yet.
