### ISSUE TITLE
getPodUrlAll should parse the https://www.w3.org/ns/pim/space# predicate

### ISSUE THREAD

**Issue by raywang999** [inrupt/solid-client-js#2033]
### Search terms you've used

pod
https

### Feature suggestion
getPodUrlAll should parse the [https://www.w3.org/ns/pim/space#](https://www.w3.org/ns/pim/space#) predicate 

[getPodUrlAll() ](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/profile_webid.html#getpodurlall) function doesn't parse the [https://www.w3.org/ns/pim/space#](https://www.w3.org/ns/pim/space#) predicate, but 
does parse the [http://www.w3.org/ns/pim/space#](http://www.w3.org/ns/pim/space#) predicate. 

### Expected functionality/enhancement
[getPodUrlAll() ](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/profile_webid.html#getpodurlall) function finds the [https://www.w3.org/ns/pim/space#](https://www.w3.org/ns/pim/space#) predicate, as well as the the [http://www.w3.org/ns/pim/space#](http://www.w3.org/ns/pim/space#) predicate. 

### Actual functionality/enhancement

Currently, [getPodUrlAll() ](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/profile_webid.html#getpodurlall) function finds the [http://www.w3.org/ns/pim/space#](http://www.w3.org/ns/pim/space#) predicate, but doesn't find the [https://www.w3.org/ns/pim/space#](https://www.w3.org/ns/pim/space#) predicate. 

### Use Cases

Self-hosters can use either prefix (https or http) to get the pod urls.

**Comment by jeswr** [comment]
http and https URIs are *not* interchangeable in RDF as URIs are compared using an exact string match.

The [solid spec](https://solidproject.org/TR/protocol#namespaces) defines `pim` as  http://www.w3.org/ns/pim/space# and so `pim:storage` is explicitly defined as http://www.w3.org/ns/pim/space#storage and so implementations *MUST* use that URI for the `pim:storage` predicate in order to correctly implement the spec.

Also note that when you *dereference* https://www.w3.org/ns/pim/space# the document you retrieve correctly uses `http` in its definition of `pim:storage`. In particular

```ts
$ npx rdf-dereference https://www.w3.org/ns/pim/space# | grep "#storage"
{"subject":"http://www.w3.org/ns/pim/space#storage","predicate":"http://www.w3.org/1999/02/22-rdf-syntax-ns#type","object":"http://www.w3.org/1999/02/22-rdf-syntax-ns#Property","graph":""},
{"subject":"http://www.w3.org/ns/pim/space#storage","predicate":"http://www.w3.org/2000/01/rdf-schema#comment","object":"\"The storage in which this workspace is, or the storage which\ncontains this resource, or a storage available to this agent to use.\"","graph":""},
{"subject":"http://www.w3.org/ns/pim/space#storage","predicate":"http://www.w3.org/2000/01/rdf-schema#label","object":"\"storage\"","graph":""},
{"subject":"http://www.w3.org/ns/pim/space#storage","predicate":"http://www.w3.org/2000/01/rdf-schema#range","object":"http://www.w3.org/ns/pim/space#Storage","graph":""},
```

I encourage you to look inspect the document downloaded when you visit https://www.w3.org/ns/pim/space# to see why this is the case. I'm also happy to answer follow up questions :)
