### ISSUE TITLE
Should we support deprecated predicate acl:defaultForNew?

### ISSUE THREAD

**Issue by megoth** [inrupt/solid-client-js#251]
**Search terms you've used**

acl, defaultForNew

**Is your feature request related to a problem? Please describe.**

I'm working on an app that uses [acl/agent#unstable_getAgentAccessAll](https://inrupt.github.io/lit-pod/docs/api/modules/_acl_agent_#unstable_getagentaccessall), and noticed that my app failed to load the default access controls for a resource. I realized the Pod I'm working on used a deprecated version of `acl:default`, namely `acl:defaultForNew`.

**Describe the solution you'd like**

This is not a bug per ce, but wondered if there is plans to support reading `acl:defaultForNew`? Could help some confussion by developers who've used the Solid systems for a while, and might still have uses of `acl:defaultForNew` hanging around.

**Describe alternatives you've considered**

If we don't want to support `acl:defaultForNew`, we might want to note that in the documentation.

**Additional context**

Don't think any extra context is required.

**Comment by NSeydoux** [comment]
Just for my understanding, is there any additional logic attached to supporting `acl:defaultForNew` compared to `acl:default` ? If not (i.e. both predicates are strictly equivalent), supporting the deprecated predicate seems rather harmless, so I don't see why we shouldn't. I can't think of a way to issue a warning to the developer that the predicate used is deprecated though, do you have anything in mind ? It's not really a big deal since the app developer isn't likely to have control over the Pod server, but it might encourage the ecosystem to use the latest version of the spec as much as possible.

**Comment by megoth** [comment]
As I understand it `acl:default` and `acl:defaultForNew` are completely equivalent, it's just that the latter has been deprecated in favor of the former for the sake of brevity. I also cannot find any references to `acl:defaultForNew` in [the WAC spec](https://github.com/solid/web-access-control-spec), so I'm fairly certain of this.

Warning is perhaps to much, but a small note in the API documentation on all methods that involve default handling might be appropriate. I reckon this might be a distracting though, and not very helpful, so I understand that this isn't a good solution.

I just know that this is going to be very annoying in those 0.1% of cases where an app aren't able to handle the deprecated version 😛

**Comment by acoburn** [comment]
There are two perspectives here: the view from the app and the view from the server. It may make sense for client apps to understand the `acl:defaultForNew` predicate is equivalent to `acl:default` in a "read" context, but not all servers support `acl:defaultForNew`. That is, I would be very careful if the client app is _writing_ ACLs to a server and expecting a server to understand `acl:defaultForNew`.

**Comment by megoth** [comment]
Yes, I'm only advocating supporting `acl:defaultForNew` as a read operation; when writing it should only do `acl:default`.

**Comment by acoburn** [comment]
@megoth excellent! I just wanted to check to make sure.

**Comment by travis** [comment]
hi all! 

just wanted to note that the current version of NSS has defaultForNew in the template ACL for the `private` directory, so all new users of existing NSS instances have defaultForNew in a pretty important ACL - I bumped into this while trying to implement a sharing dialog for a resource stored in that directory.

I have this fixed in a PR here: 

https://github.com/inrupt/solid-client-js/pull/321

but don't have a ton of certainty about the fix or the unit testing - it seems to work in a test app I'm working on but wouldn't be surprised if I've missed something.
